#
# Global properties (common for all environments)
#
spring:
   datasource:
      platform: hsqldb
application:
   message:
      text: Hello Spring!
format:
   date: dd-MM-yyyy
   time: HH:mm:ss
   datetime: dd-MM-yyyy HH:mm:ss