#
# Properties valid for development
#
environment:
   name: Development
   version: 0.1
datasource:
   primary:
      url: jdbc:mysql://localhost:3306/drupal7
      username: drupal
      password: drupal
      platform: mysql
      driverClassName: com.mysql.jdbc.Driver
   secondary:
      url: jdbc:mysql://localhost:3306/szkolrwu_psoslo_db
      username: szkolrwu_dbuser1
      password: pkO5oEay#;
      platform: mysql
      driverClassName: com.mysql.jdbc.Driver