#
# Global properties (common for all environments)
#
spring:
   datasource:
      url: jdbc:mysql://localhost:3306/drupal7
      username: drupal
      password: drupal
      platform: mysql
#      platform: hsqldb
application:
   message:
      text: Hello Spring!
format:
   date: dd-MM-yyyy
   time: HH:mm:ss
   datetime: dd-MM-yyyy HH:mm:ss