INSERT INTO APPLES (NAME) VALUES ('Test apple 1');
INSERT INTO APPLES (NAME) VALUES ('Test apple 2');
INSERT INTO APPLES (NAME) VALUES ('Test apple 3');
INSERT INTO ORANGES (SIZE) VALUES ('Size 1');
INSERT INTO ORANGES (SIZE) VALUES ('Size 2');
INSERT INTO ORANGES (SIZE) VALUES ('Size 3');